- name: Collect Server IP
  debug:
    msg: "{{ ansible_ssh_host }}"

- name: Collect Server ARCH
  debug: 
      msg: '{{ansible_architecture}}'

- name: Gather Ubuntu version
  command: lsb_release -rs
  register: os_version

- name: Ensure Debian version is a float
  set_fact:
    os_version_number: "{{ os_version.stdout | float }}"

- name: Debug Debian version number
  debug:
    msg: "The Debian version number is {{ os_version_number }}"