- name: Install optional packages through retropie setup script
  shell: RetroPie-Setup/retropie_packages.sh {{item}}
  with_items: '{{OPT_PACKAGES}}'
  args:
    executable: /bin/bash
  tags: packages

# Install the playstation bios file for better psx compatibility 
- name: Download PlayStation BIOS file
  ansible.builtin.get_url:
    url: "https://archive.org/download/PlayStationBIOSFilesNAEUJP/{{item}}"
    dest: "/home/pi/RetroPie/BIOS/{{item}}"
    mode: '0644'
  with_items:
   - 'scph5500.bin' #NA
   - 'scph5501.bin' #EU
   - 'scph5502.bin' #JAPAN
  tags: bios