- name: Install Packages through retropie script
  shell: RetroPie-Setup/retropie_packages.sh {{item}}
  with_items: 
    - 'steamlink'
    - 'skyscraper'
    - 'lr-prboom'
    - 'darkplaces-quake'
    - 'eduke32'
    - 'ioquake3'
    - 'kodi'
    - 'lzdoom'
  args:
    executable: /bin/bash
  tags: packages