#Steam Link Fixes
  # Disable overscaning to fix steamlink black screen issue
- name: Uncomment disable_overscan=1 in /boot/config.txt
  lineinfile:
    path: /boot/config.txt
    regexp: '^#disable_overscan=1'
    line: 'disable_overscan=1'
    state: present
  tags: config
- name: Ensure changes are saved to disk
  command: sync
  tags: config

  # Disable false positive video memory check
- name: Ensure SteamLink directory exists
  file:
    path: /home/pi/.local/share/SteamLink
    state: directory
    mode: '0755'
  tags: config
- name: Create .ignore_gpumem file
  file:
    path: /home/pi/.local/share/SteamLink/.ignore_gpumem
    state: touch
    mode: '0644'
  tags: config

# OS Specific Fixes
  # Make linux console font bigger 
- name: Set console font and size for tv
  command: setfont /usr/share/consolefonts/Lat15-TerminusBold20x10.psf.gz
  tags: config

- name: Edit console-setup file
  blockinfile:
    path: /etc/default/console-setup
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Add your changes here
      # Example change:
      FONTFACE="TerminusBold"
      FONTSIZE="100x80"
  tags: config

# Enable 4k 60hz over microHDMI
- name: Enable 4k60hz on PI
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Add your changes here
      hdmi_enable_4kp60=1
  tags: config