- name: Change the SSH port to {{ssh_port}}
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port {{ssh_port}}'
    state: present

- name: Restart SSH service to apply changes
  service:
    name: ssh
    state: restarted

- name: Ensure SSH service is enabled at boot
  service:
    name: ssh
    enabled: yes
